security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
        login_form:
            pattern: ^/login
            stateless: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator

    access_control:
        - { path: ^/lessons, roles: ROLE_USER }
        - { path: ^/quiz, roles: ROLE_USER }
        - { path: ^/admin/quiz, roles: ROLE_ADMIN }
        - { path: ^/admin/lesson, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_ADMIN }



        
