controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_quiz_complete:
    path: '/quiz/{id}/complete'
    controller: 'App\Controller\QuizController::completeQuizAction'
    methods: ['GET']